- name: Create network confi on a palo alto networks firewall
  hosts: 192.168.59.129
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
  
  tasks:
  - name: Load Variables
    include_vars: vars.yml

  - name: Push Interface Settings to the firewall
    changed_when: false
    panos_interface:
      provider: '{{ provider }}'
      if_name: '{{ item.name }}'
      ip: ['{{ item.ip }}']
      zone_name: '{{ item.zone }}'
      mode: '{{ item.mode }}'
      enable_dhcp: no
      commit: no
    with_items: '{{ interfaces }}'